services:
    postgres:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=S3cret
            - POSTGRES_USER=testuser
            - POSTGRES_DB=testcase